# -*- coding: utf-8 -*-
"""team_asparagine_script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nHr0-gwEebrjsLU0SmFD9ydqAbFW8KoP
"""

import pandas as pd

data = {
    "name": [
        "Ayşenur Akcan",
        "Oni David Sunday",
        "Noor Ul Ain Amir",
        "Özlem Kalkan",
        "Daria Kriuchkova",
        "Minenhle Mayisela"
    ],
    "slack_username": [
        "@Ayşenur Akcan",
        "@Sunday",
        "@Noor Ul Ain Amir",
        "@anyavala",
        "@Daria",
        "@Minenhle Mayisela"
    ],
    "country": [
        "Türkiye",
        "Nigeria",
        "Pakistan",
        "Türkiye / Ukraine",
        "Ukraine",
        "Eswatini / South Africa"
    ],
    "hobby": [
        "Mending something",
        "Reading",
        "Baking",
        "Doing sport",
        "Knitting",
        "Reading"
    ],
    "affiliation": [
        "Istanbul Technical University",
        "Wageningen University and Research",
        "Forman Christian College, University",
        "Bonn University",
        "Kharkiv Polytechnic Institute",
        "University of the Witwatersrand"
    ],
    "fav_gene_seq": [
        "TP53-ATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCCCCTC",
        "AKT1-TCTTCTCCCACTCCCCAGCAAAGTCCCCCTTTTGTGAGTG",
        "SHH-ACAAGCTCTCCAGGCTTGCTACCATTTAAAATCAGACTCT",
        "8OHY-ATGGCTCAAAGCACTGTTTTGCCTATGCACTGTTTATACG",
        "BRCA1-ATGGAAGTTGTCATTTTGTGTTTCCAGGATTTATTTGCTC",
        "LMNA-GACAAATTCCTTGACCCGAGGAGGATAGGGATGTGGCCTT"
    ]
}

df = pd.DataFrame(data)
#print(df)

class TeamAsparagine:
    def __init__(self, dataframe):
        self.df = dataframe

    def show_members(self):
        print("Team Members:")
        for name in self.df['name']:
            print(f"- {name}")
        print()

    def show_usernames(self):
        print("Slack Usernames:")
        for _, row in self.df.iterrows():
            print(f"{row['name']}: {row['slack_username']}")
        print()

    def show_countries(self):
        print("Countries:")
        for _, row in self.df.iterrows():
            print(f"{row['name']}: {row['country']}")
        print()

    def show_hobbies(self):
        print("Hobbies:")
        for _, row in self.df.iterrows():
            print(f"{row['name']}: {row['hobby']}")
        print()

    def show_affiliations(self):
        print("Affiliations:")
        for _, row in self.df.iterrows():
            print(f"{row['name']}: {row['affiliation']}")
        print()

    def show_fav_sequences(self):
        print("Favourite DNA Sequences:")
        for _, row in self.df.iterrows():
            print(f"{row['name']}: {row['fav_gene_seq']}")
        print()

if __name__ == "__main__":
    team = TeamAsparagine(df)
    team.show_members()
    team.show_usernames()
    team.show_countries()
    team.show_hobbies()
    team.show_affiliations()
    team.show_fav_sequences()

